In [1]:
# Importing the pandas library and giving alias
import pandas as pd

In [2]:
# Reading a csv file and assigning it to a data frame object
df = pd.read_csv(r'C:\Users\nawaz\Desktop\python for data engineering\datasets\countries of the world.csv')
df

             Country                               Region
0       Afghanistan         ASIA (EX. NEAR EAST)
1           Albania   EASTERN EUROPE
2           Algeria   NORTHERN AFRICA
3    American Samoa   OCEANIA
4           Andorra   WESTERN EUROPE
..               ...                                  ...
222       West Bank   NEAR EAST
223  Western Sahara   NORTHERN AFRICA
224           Yemen   NEAR EAST
225          Zambia   SUB-SAHARAN AFRICA
226        Zimbabwe   SUB-SAHARAN AFRICA

[227 rows x 2 columns]

In [21]:
# Reading a txt file and reassigning it to the same data frame object
df = pd.read_table(r'C:\Users\nawaz\Desktop\python for data engineering\datasets\countries of the world.txt')
df

             Country                               Region
0       Afghanistan         ASIA (EX. NEAR EAST)
1           Albania   EASTERN EUROPE
2           Algeria   NORTHERN AFRICA
3    American Samoa   OCEANIA
4           Andorra   WESTERN EUROPE
..               ...                                  ...
222       West Bank   NEAR EAST
223  Western Sahara   NORTHERN AFRICA
224           Yemen   NEAR EAST
225          Zambia   SUB-SAHARAN AFRICA
226        Zimbabwe   SUB-SAHARAN AFRICA

[227 rows x 2 columns]

In [30]:
# Here reading a json file, json files are semi-structured in nature
df = pd.read_json(r"C:\Users\nawaz\Desktop\python for data engineering\datasets\json_sample.json")
df

,12 Strong,A Fantastic Woman (Una Mujer Fantástica),All The Money In The World,Bilal: A New Breed Of Hero,Call Me By Your Name,Darkest Hour,Den Of Thieves,Ferdinand,Fifty Shades Freed,Film Stars Don'T Die In Liverpool,Forever My Girl,Golden Exits,Hostiles,"I, Tonya",Insidious: The Last Key,Jumanji: Welcome To The Jungle,Mary And The Witch'S Flower,Maze Runner: The Death Cure,Molly'S Game,Paddington 2,Padmaavat,Permission,Peter Rabbit,Phantom Thread,Pitch Perfect 3,Proud Mary,Sanpo Suru Shinryakusha,Star Wars: The Last Jedi,The 15:17 To Paris,The Commuter,The Disaster Artist,The Greatest Showman,The Insult (L'Insulte),The Post,The Shape Of Water,"Three Billboards Outside Ebbing, Missouri",Till The End Of The World,Winchester
0,"{'Genre': 'Action', 'Gross': '$453,173', 'IMDB...","{'popcornscore': 83, 'rating': 'R', 'tomatosco...","{'popcornscore': 71, 'rating': 'R', 'tomatosco...","{'popcornscore': 91, 'rating': 'PG13', 'tomato...","{'popcornscore': 87, 'rating': 'R', 'tomatosco...","{'popcornscore': 84, 'rating': 'PG13', 'tomato...","{'Genre': 'Action', 'Gross': '$491,898', 'IMDB...","{'popcornscore': 49, 'rating': 'PG', 'tomatosc...","{'Genre': 'Drama', 'Gross': 'unknown', 'IMDB M...","{'popcornscore': 69, 'rating': 'R', 'tomatosco...","{'popcornscore': 91, 'rating': 'PG', 'tomatosc...","{'Genre': 'Drama', 'Gross': 'unknown', 'IMDB M...","{'Genre': 'Adventure', 'Gross': '$548,886', 'I...","{'popcornscore': 89, 'rating': 'R', 'tomatosco...","{'popcornscore': 51, 'rating': 'PG13', 'tomato...","{'Genre': 'Action', 'Gross': '$760,867', 'IMDB...","{'popcornscore': 78, 'rating': 'PG', 'tomatosc...","{'Genre': 'Action', 'Gross': '$720,463', 'IMDB...","{'popcornscore': 85, 'rating': 'R', 'tomatosco...","{'Genre': 'Animation', 'Gross': '$184,414', 'I...","{'popcornscore': 62, 'rating': 'NR', 'tomatosc...","{'Genre': 'Comedy', 'Gross': 'unknown', 'IMDB ...","{'Genre': 'Animation', 'Gross': 'unknown', 'IM...","{'popcornscore': 68, 'rating': 'R', 'tomatosco...","{'popcornscore': 52, 'rating': 'PG13', 'tomato...","{'popcornscore': 56, 'rating': 'R', 'tomatosco...","{'Genre': 'Drama', 'Gross': 'unknown', 'IMDB M...","{'popcornscore': 48, 'rating': 'PG13', 'tomato...","{'Genre': 'Drama', 'Gross': 'unknown', 'IMDB M...","{'popcornscore': 48, 'rating': 'PG13', 'tomato...","{'popcornscore': 89, 'rating': 'R', 'tomatosco...","{'Genre': 'Biography', 'Gross': '$627,248', 'I...","{'popcornscore': 86, 'rating': 'R', 'tomatosco...","{'Genre': 'Biography', 'Gross': '$463,228', 'I...","{'Genre': 'Adventure', 'Gross': '$448,287', 'I...","{'popcornscore': 87, 'rating': 'R', 'tomatosco...","{'popcornscore': -1, 'rating': 'NR', 'tomatosc...","{'Genre': 'Biography', 'Gross': '$696,786', 'I..."

In [6]:
# Reading an excel spreadsheet
df = pd.read_excel(r"C:\Users\nawaz\Desktop\python for data engineering\datasets\world_population_excel_workbook.xlsx", sheet_name = 'Sheet1')
df

     Rank CCA3            Country           Capital
0      36  AFG        Afghanistan             Kabul
1     138  ALB            Albania            Tirana
2      34  DZA            Algeria           Algiers
3     213  ASM     American Samoa         Pago Pago
4     203  AND            Andorra  Andorra la Vella
..    ...  ...                ...               ...
229   226  WLF  Wallis and Futuna          Mata-Utu
230   172  ESH     Western Sahara         El AaiÃºn
231    46  YEM              Yemen             Sanaa
232    63  ZMB             Zambia            Lusaka
233    74  ZWE           Zimbabwe            Harare

[234 rows x 4 columns]

In [27]:
# Setting the options to show arbitrary maximum number of rows and columns
pd.set_option('display.max.rows', 235)
pd.set_option('display.max.columns', 40)

In [36]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 234 entries, 0 to 233
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Rank     234 non-null    int64
 1   CCA3     234 non-null    str
 2   Country  234 non-null    str
 3   Capital  234 non-null    str
dtypes: int64(1), str(3)
memory usage: 12.1 KB

In [13]:
# Shows some aggregate functions that could be performed on the int / float value columns
df.describe()

             Rank
count  234.000000
mean   117.500000
std     67.694165
min      1.000000
25%     59.250000
50%    117.500000
75%    175.750000
max    234.000000

In [37]:
df.head()

   Rank CCA3         Country           Capital
0    36  AFG     Afghanistan             Kabul
1   138  ALB         Albania            Tirana
2    34  DZA         Algeria           Algiers
3   213  ASM  American Samoa         Pago Pago
4   203  AND         Andorra  Andorra la Vella

In [38]:
df.tail(11)

     Rank CCA3            Country       Capital
223   133  URY            Uruguay    Montevideo
224    43  UZB         Uzbekistan      Tashkent
225   181  VUT            Vanuatu     Port-Vila
226   234  VAT       Vatican City  Vatican City
227    51  VEN          Venezuela       Caracas
228    16  VNM            Vietnam         Hanoi
229   226  WLF  Wallis and Futuna      Mata-Utu
230   172  ESH     Western Sahara     El AaiÃºn
231    46  YEM              Yemen         Sanaa
232    63  ZMB             Zambia        Lusaka
233    74  ZWE           Zimbabwe        Harare

In [46]:
# This function can accept both strings and integers as input, depending upon the index data type
df.loc[222]

Rank                                200
CCA3                                VIR
Country    United States Virgin Islands
Capital                Charlotte Amalie
Name: 222, dtype: object

In [50]:
# Gets an index (integer only) and returns the whole row
df.iloc[111]

Rank          151
CCA3          LVA
Country    Latvia
Capital      Riga
Name: 111, dtype: object

In [4]:
# Shows the total number of rows and columns
df.shape

(227, 2)