In [4]:
import pandas as pd

In [5]:
df1 = pd.read_csv(r"C:\Users\nawaz\Desktop\LOTR.csv")
df1

   FellowshipID FirstName     Skills
0          1001     Frodo     Hiding
1          1002   Samwise  Gardening
2          1003   Gandalf     Spells
3          1004    Pippin  Fireworks

In [6]:
df2 = pd.read_csv(r"C:\Users\nawaz\Desktop\LOTR 2.csv")
df2

   FellowshipID FirstName   Age
0          1001     Frodo    50
1          1002   Samwise    39
2          1006   Legolas  2931
3          1007    Elrond  6520
4          1008  Barromir    51

In [43]:
df1.merge(df2) # 'Inner' is the default

   FellowshipID FirstName     Skills  Age
0          1001     Frodo     Hiding   50
1          1002   Samwise  Gardening   39

In [48]:
# on keyword is used for checking matching columns. The columns in the on list will appear only once, rest if common will appear
# as duplicates. 
df1.merge(df2, how = 'outer', on = ['FellowshipID'])

   FellowshipID FirstName_x     Skills FirstName_y     Age
0          1001       Frodo     Hiding       Frodo    50.0
1          1002     Samwise  Gardening     Samwise    39.0
2          1003     Gandalf     Spells         NaN     NaN
3          1004      Pippin  Fireworks         NaN     NaN
4          1006         NaN        NaN     Legolas  2931.0
5          1007         NaN        NaN      Elrond  6520.0
6          1008         NaN        NaN    Barromir    51.0

In [53]:
# If 'on' is omitted by default Pandas will use all common columns for matching and those columns will appear only once
df1.merge(df2, how = 'outer')

   FellowshipID FirstName     Skills     Age
0          1001     Frodo     Hiding    50.0
1          1002   Samwise  Gardening    39.0
2          1003   Gandalf     Spells     NaN
3          1004    Pippin  Fireworks     NaN
4          1006   Legolas        NaN  2931.0
5          1007    Elrond        NaN  6520.0
6          1008  Barromir        NaN    51.0

In [60]:
# Exactly like left exclusive or right exclusive join in SQL
df1.merge(df2, how = 'right_anti', on = ['FellowshipID', 'FirstName'])

   FellowshipID FirstName Skills   Age
2          1006   Legolas    NaN  2931
3          1007    Elrond    NaN  6520
4          1008  Barromir    NaN    51

In [79]:
df1.join(df2, how = 'outer', on = 'FellowshipID', lsuffix = '_left', rsuffix = '_right')

,FellowshipID,FellowshipID_left,FirstName_left,Skills,FellowshipID_right,FirstName_right,Age
NaN,0,NaN,NaN,NaN,1001.0,Frodo,50.0
NaN,1,NaN,NaN,NaN,1002.0,Samwise,39.0
NaN,2,NaN,NaN,NaN,1006.0,Legolas,2931.0
NaN,3,NaN,NaN,NaN,1007.0,Elrond,6520.0
NaN,4,NaN,NaN,NaN,1008.0,Barromir,51.0
0.0,1001,1001.0,Frodo,Hiding,NaN,NaN,NaN
1.0,1002,1002.0,Samwise,Gardening,NaN,NaN,NaN
2.0,1003,1003.0,Gandalf,Spells,NaN,NaN,NaN
3.0,1004,1004.0,Pippin,Fireworks,NaN,NaN,NaN

In [81]:
# Best use join when working with indexes otherwise its complicated than merge and also involves more work
df3 = df1.set_index('FellowshipID')
df3

             FirstName     Skills
FellowshipID
1001             Frodo     Hiding
1002           Samwise  Gardening
1003           Gandalf     Spells
1004            Pippin  Fireworks

In [82]:
df4 = df2.set_index('FellowshipID')
df4

             FirstName   Age
FellowshipID
1001             Frodo    50
1002           Samwise    39
1006           Legolas  2931
1007            Elrond  6520
1008          Barromir    51

In [84]:
df3.join(df4, how = 'outer', lsuffix = '_left', rsuffix = '_right')

             FirstName_left     Skills FirstName_right     Age
FellowshipID
1001                  Frodo     Hiding           Frodo    50.0
1002                Samwise  Gardening         Samwise    39.0
1003                Gandalf     Spells             NaN     NaN
1004                 Pippin  Fireworks             NaN     NaN
1006                    NaN        NaN         Legolas  2931.0
1007                    NaN        NaN          Elrond  6520.0
1008                    NaN        NaN        Barromir    51.0

In [89]:
df3.join(df4, how = 'outer', lsuffix = '_left', rsuffix = '_right')

             FirstName_left     Skills FirstName_right     Age
FellowshipID
1001                  Frodo     Hiding           Frodo    50.0
1002                Samwise  Gardening         Samwise    39.0
1003                Gandalf     Spells             NaN     NaN
1004                 Pippin  Fireworks             NaN     NaN
1006                    NaN        NaN         Legolas  2931.0
1007                    NaN        NaN          Elrond  6520.0
1008                    NaN        NaN        Barromir    51.0

In [110]:
# axis = 0 will give the common columns for inner join
pd.concat([df3, df4], join = 'inner', axis = 0)

             FirstName
FellowshipID
1001             Frodo
1002           Samwise
1003           Gandalf
1004            Pippin
1001             Frodo
1002           Samwise
1006           Legolas
1007            Elrond
1008          Barromir

In [120]:
# axis = 1 will give the common rows for inner join
pd.concat([df3, df4], join = 'inner', axis = 1)

             FirstName     Skills FirstName  Age
FellowshipID
1001             Frodo     Hiding     Frodo   50
1002           Samwise  Gardening   Samwise   39

In [123]:
pd.concat([df3, df4], join = 'outer')

             FirstName     Skills     Age
FellowshipID
1001             Frodo     Hiding     NaN
1002           Samwise  Gardening     NaN
1003           Gandalf     Spells     NaN
1004            Pippin  Fireworks     NaN
1001             Frodo        NaN    50.0
1002           Samwise        NaN    39.0
1006           Legolas        NaN  2931.0
1007            Elrond        NaN  6520.0
1008          Barromir        NaN    51.0

In [ ]:
# By default merge() is 'inner' and join() is 'left'.
# Use merge() when combining datasets using matching columns, such as joining customers and orders using CustomerID.
# Use join() when the data is already indexed meaningfully, or when you want to combine DataFrames using their indexes.

In [ ]:
# NaN is not a string, it's a special floating-point value. To accomodate the float, pandas will convert the integer values of
# the column into float. That's why if we previously had 50 it will become 50.0 in a column containing NaN.